deploy: build deploy-stack deploy-s3

deploy-stack:
	npm run deploy-stack

deploy-s3:
	npm run deploy-s3

build: npm-install
	npm run build:static

npm-install:
	npm i

remove:
	npm run remove

start: npm-install
	npm run start